/**
 * ConceptBuilder game themes.
 * Each theme maps to a set of items + a VisualTheme that makes the game look like
 * the subject matter (space, rainbow, jungle, etc.).
 */

import type { GameItem, VisualTheme } from './ConceptBuilder'

export interface GameTheme {
  id: string
  title: string
  description: string
  emoji: string
  /** Recommended minimum age */
  minAge: number
  items: GameItem[]
  visual: VisualTheme
}

export const GAME_THEMES: GameTheme[] = [
  {
    id: 'solar-system',
    title: 'Build the Solar System',
    description: 'Order the planets from closest to farthest from the Sun',
    emoji: '🪐',
    minAge: 5,
    items: [
      { id: 'mercury', label: 'Mercury', correctIndex: 0, image: '☿' },
      { id: 'venus',   label: 'Venus',   correctIndex: 1, image: '♀' },
      { id: 'earth',   label: 'Earth',   correctIndex: 2, image: '🌍' },
      { id: 'mars',    label: 'Mars',    correctIndex: 3, image: '🔴' },
      { id: 'jupiter', label: 'Jupiter', correctIndex: 4, image: '🟠' },
      { id: 'saturn',  label: 'Saturn',  correctIndex: 5, image: '💛' },
    ],
    visual: {
      wrapperClass: 'bg-gradient-to-b from-slate-950 via-blue-950 to-indigo-950',
      decorations: [
        { emoji: '✨', style: { top: '4%',  left: '7%',  fontSize: '0.8rem', opacity: '0.8' } },
        { emoji: '⭐', style: { top: '8%',  left: '80%', fontSize: '0.6rem', opacity: '0.7' } },
        { emoji: '✨', style: { top: '18%', left: '3%',  fontSize: '0.5rem', opacity: '0.6' } },
        { emoji: '🌟', style: { top: '22%', right: '6%', fontSize: '1rem',   opacity: '0.5' } },
        { emoji: '⭐', style: { top: '35%', left: '5%',  fontSize: '0.7rem', opacity: '0.8' } },
        { emoji: '✨', style: { top: '50%', right: '4%', fontSize: '0.9rem', opacity: '0.6' } },
        { emoji: '⭐', style: { top: '65%', left: '8%',  fontSize: '0.5rem', opacity: '0.7' } },
        { emoji: '🌟', style: { top: '75%', right: '7%', fontSize: '0.7rem', opacity: '0.5' } },
        { emoji: '✨', style: { top: '88%', left: '12%', fontSize: '0.6rem', opacity: '0.8' } },
        { emoji: '🌙', style: { top: '6%',  left: '44%', fontSize: '2.5rem', opacity: '0.15' } },
        { emoji: '🪐', style: { top: '40%', left: '48%', fontSize: '6rem',   opacity: '0.04' } },
      ],
      itemCardClass: 'bg-blue-950/70 border-blue-400/40 backdrop-blur-sm shadow-blue-500/30',
      itemTextClass: 'text-blue-100',
      zoneNumberClass: 'text-blue-300/70',
      zoneEmptyClass: 'border-dashed border-blue-400/30 bg-blue-900/20',
      poolClass: 'border-blue-700/30 bg-blue-950/40',
      dropAreaClass: 'bg-indigo-950/50 border-indigo-700/30',
      sectionLabelClass: 'text-blue-300/60',
      titleClass: 'text-white drop-shadow-lg',
      subtitleClass: 'text-blue-200/70',
      progressFill: '#60a5fa',
      progressTrackClass: 'bg-blue-900/50',
      backBarClass: 'border-blue-800/40 bg-slate-950/80 backdrop-blur-sm',
      backButtonClass: 'text-blue-300',
    },
  },
  {
    id: 'rainbow',
    title: 'Sort the Rainbow',
    description: 'Arrange the colours of the rainbow in the right order',
    emoji: '🌈',
    minAge: 3,
    items: [
      { id: 'red',    label: 'Red',    correctIndex: 0, image: '🔴' },
      { id: 'orange', label: 'Orange', correctIndex: 1, image: '🟠' },
      { id: 'yellow', label: 'Yellow', correctIndex: 2, image: '🟡' },
      { id: 'green',  label: 'Green',  correctIndex: 3, image: '🟢' },
      { id: 'blue',   label: 'Blue',   correctIndex: 4, image: '🔵' },
      { id: 'violet', label: 'Violet', correctIndex: 5, image: '🟣' },
    ],
    visual: {
      wrapperClass: 'bg-gradient-to-b from-sky-400 via-sky-300 to-blue-200',
      decorations: [
        { emoji: '⛅', style: { top: '5%',  left: '10%', fontSize: '2.5rem', opacity: '0.6' } },
        { emoji: '☁️', style: { top: '3%',  left: '55%', fontSize: '3rem',   opacity: '0.5' } },
        { emoji: '⛅', style: { top: '8%',  right: '8%', fontSize: '2rem',   opacity: '0.55' } },
        { emoji: '☀️', style: { top: '2%',  left: '2%',  fontSize: '3.5rem', opacity: '0.7' } },
        { emoji: '🌈', style: { top: '30%', left: '50%', fontSize: '8rem',   opacity: '0.06', transform: 'rotate(-15deg)' } },
        { emoji: '💧', style: { top: '70%', left: '15%', fontSize: '1rem',   opacity: '0.4' } },
        { emoji: '💧', style: { top: '75%', left: '60%', fontSize: '0.8rem', opacity: '0.35' } },
        { emoji: '💧', style: { top: '80%', left: '40%', fontSize: '1.2rem', opacity: '0.3' } },
      ],
      itemCardClass: 'bg-white/85 border-white shadow-md shadow-sky-200/50',
      itemTextClass: 'text-sky-900',
      zoneNumberClass: 'text-sky-700/70',
      zoneEmptyClass: 'border-dashed border-sky-300/60 bg-white/30',
      poolClass: 'border-white/50 bg-white/30 backdrop-blur-sm',
      dropAreaClass: 'bg-white/20 border-white/40 backdrop-blur-sm',
      sectionLabelClass: 'text-sky-700/70',
      titleClass: 'text-sky-900 drop-shadow',
      subtitleClass: 'text-sky-700',
      progressFill: '#0ea5e9',
      progressTrackClass: 'bg-sky-200/60',
      backBarClass: 'border-sky-300/40 bg-sky-400/50 backdrop-blur-sm',
      backButtonClass: 'text-sky-800',
    },
  },
  {
    id: 'numbers',
    title: 'Count to 8',
    description: 'Put the numbers in order from 1 to 8',
    emoji: '🔢',
    minAge: 3,
    items: [
      { id: 'one',   label: '1 One',   correctIndex: 0, image: '1️⃣' },
      { id: 'two',   label: '2 Two',   correctIndex: 1, image: '2️⃣' },
      { id: 'three', label: '3 Three', correctIndex: 2, image: '3️⃣' },
      { id: 'four',  label: '4 Four',  correctIndex: 3, image: '4️⃣' },
      { id: 'five',  label: '5 Five',  correctIndex: 4, image: '5️⃣' },
      { id: 'six',   label: '6 Six',   correctIndex: 5, image: '6️⃣' },
      { id: 'seven', label: '7 Seven', correctIndex: 6, image: '7️⃣' },
      { id: 'eight', label: '8 Eight', correctIndex: 7, image: '8️⃣' },
    ],
    visual: {
      wrapperClass: 'bg-gradient-to-b from-amber-400 via-yellow-300 to-orange-300',
      decorations: [
        { emoji: '➕', style: { top: '6%',  left: '8%',  fontSize: '1.5rem', opacity: '0.25' } },
        { emoji: '➖', style: { top: '12%', right: '10%',fontSize: '1.5rem', opacity: '0.25' } },
        { emoji: '✖️', style: { top: '30%', left: '4%',  fontSize: '1.2rem', opacity: '0.2'  } },
        { emoji: '➕', style: { top: '55%', right: '6%', fontSize: '1.8rem', opacity: '0.2'  } },
        { emoji: '🧩', style: { top: '70%', left: '7%',  fontSize: '1.5rem', opacity: '0.3'  } },
        { emoji: '🔢', style: { top: '35%', left: '48%', fontSize: '8rem',   opacity: '0.05' } },
        { emoji: '⭐', style: { top: '80%', right: '9%', fontSize: '1.5rem', opacity: '0.3'  } },
        { emoji: '🌟', style: { top: '20%', left: '45%', fontSize: '1rem',   opacity: '0.3'  } },
      ],
      itemCardClass: 'bg-white/90 border-orange-200 shadow-md shadow-orange-300/30',
      itemTextClass: 'text-orange-800',
      zoneNumberClass: 'text-orange-700/70',
      zoneEmptyClass: 'border-dashed border-orange-300/50 bg-white/30',
      poolClass: 'border-orange-300/40 bg-white/30',
      dropAreaClass: 'bg-orange-100/30 border-orange-300/40',
      sectionLabelClass: 'text-orange-700/70',
      titleClass: 'text-orange-900 drop-shadow',
      subtitleClass: 'text-orange-700',
      progressFill: '#f97316',
      progressTrackClass: 'bg-orange-200/60',
      backBarClass: 'border-orange-300/40 bg-amber-400/60 backdrop-blur-sm',
      backButtonClass: 'text-orange-800',
    },
  },
  {
    id: 'seasons',
    title: 'Order the Seasons',
    description: 'Arrange the four seasons in the correct yearly order',
    emoji: '🍂',
    minAge: 4,
    items: [
      { id: 'spring', label: 'Spring', correctIndex: 0, image: '🌸' },
      { id: 'summer', label: 'Summer', correctIndex: 1, image: '☀️' },
      { id: 'autumn', label: 'Autumn', correctIndex: 2, image: '🍂' },
      { id: 'winter', label: 'Winter', correctIndex: 3, image: '❄️' },
    ],
    visual: {
      wrapperClass: 'bg-gradient-to-b from-orange-900 via-amber-800 to-orange-700',
      decorations: [
        { emoji: '🍂', style: { top: '5%',  left: '6%',  fontSize: '2rem',   opacity: '0.4'  } },
        { emoji: '🍁', style: { top: '10%', right: '8%', fontSize: '1.8rem', opacity: '0.35' } },
        { emoji: '🍃', style: { top: '20%', left: '4%',  fontSize: '1.2rem', opacity: '0.3'  } },
        { emoji: '🍂', style: { top: '35%', right: '5%', fontSize: '2.5rem', opacity: '0.3'  } },
        { emoji: '🍁', style: { top: '55%', left: '7%',  fontSize: '1.5rem', opacity: '0.4'  } },
        { emoji: '🍃', style: { top: '70%', right: '6%', fontSize: '2rem',   opacity: '0.35' } },
        { emoji: '🍂', style: { top: '85%', left: '5%',  fontSize: '1.8rem', opacity: '0.3'  } },
        { emoji: '🍁', style: { top: '88%', right: '9%', fontSize: '1.2rem', opacity: '0.25' } },
        { emoji: '🍂', style: { top: '40%', left: '48%', fontSize: '9rem',   opacity: '0.05' } },
      ],
      itemCardClass: 'bg-amber-100/20 border-amber-300/50 backdrop-blur-sm shadow-amber-900/30',
      itemTextClass: 'text-amber-50',
      zoneNumberClass: 'text-amber-300/70',
      zoneEmptyClass: 'border-dashed border-amber-300/40 bg-amber-900/20',
      poolClass: 'border-amber-600/30 bg-amber-900/30',
      dropAreaClass: 'bg-orange-800/30 border-orange-600/30',
      sectionLabelClass: 'text-amber-300/60',
      titleClass: 'text-amber-50 drop-shadow-lg',
      subtitleClass: 'text-amber-200/70',
      progressFill: '#f59e0b',
      progressTrackClass: 'bg-amber-900/50',
      backBarClass: 'border-amber-700/40 bg-orange-900/70 backdrop-blur-sm',
      backButtonClass: 'text-amber-200',
    },
  },
  {
    id: 'alphabet',
    title: 'A B C Order',
    description: 'Place the letters in alphabetical order',
    emoji: '🔤',
    minAge: 4,
    items: [
      { id: 'a', label: 'A', correctIndex: 0, image: '🅰️' },
      { id: 'b', label: 'B', correctIndex: 1, image: '🅱️' },
      { id: 'c', label: 'C', correctIndex: 2, image: '🇨' },
      { id: 'd', label: 'D', correctIndex: 3, image: '🇩' },
      { id: 'e', label: 'E', correctIndex: 4, image: '🇪' },
    ],
    visual: {
      wrapperClass: 'bg-gradient-to-b from-violet-700 via-purple-600 to-pink-500',
      decorations: [
        { emoji: '🅰️', style: { top: '4%',  left: '5%',  fontSize: '3rem',   opacity: '0.15' } },
        { emoji: 'B',  style: { top: '15%', right: '4%', fontSize: '4rem',   opacity: '0.1',  fontWeight: '900' } },
        { emoji: 'C',  style: { top: '30%', left: '3%',  fontSize: '3.5rem', opacity: '0.1',  fontWeight: '900' } },
        { emoji: 'D',  style: { top: '50%', right: '5%', fontSize: '4rem',   opacity: '0.1',  fontWeight: '900' } },
        { emoji: 'E',  style: { top: '65%', left: '4%',  fontSize: '3rem',   opacity: '0.1',  fontWeight: '900' } },
        { emoji: '⭐', style: { top: '8%',  left: '50%', fontSize: '1.2rem', opacity: '0.4'  } },
        { emoji: '✨', style: { top: '75%', right: '6%', fontSize: '1rem',   opacity: '0.5'  } },
        { emoji: '🔤', style: { top: '38%', left: '46%', fontSize: '8rem',   opacity: '0.05' } },
      ],
      itemCardClass: 'bg-white/90 border-pink-200 shadow-md shadow-purple-500/20',
      itemTextClass: 'text-purple-800',
      zoneNumberClass: 'text-pink-200/80',
      zoneEmptyClass: 'border-dashed border-pink-300/50 bg-white/20',
      poolClass: 'border-white/30 bg-white/15 backdrop-blur-sm',
      dropAreaClass: 'bg-purple-800/30 border-purple-400/30',
      sectionLabelClass: 'text-pink-200/70',
      titleClass: 'text-white drop-shadow-lg',
      subtitleClass: 'text-pink-100/80',
      progressFill: '#ec4899',
      progressTrackClass: 'bg-purple-800/50',
      backBarClass: 'border-purple-500/40 bg-violet-800/70 backdrop-blur-sm',
      backButtonClass: 'text-pink-200',
    },
  },
  {
    id: 'food-chain',
    title: 'The Food Chain',
    description: 'Order the food chain from smallest to biggest',
    emoji: '🦁',
    minAge: 6,
    items: [
      { id: 'sun',      label: 'Sun',      correctIndex: 0, image: '☀️' },
      { id: 'plant',    label: 'Plant',    correctIndex: 1, image: '🌿' },
      { id: 'bug',      label: 'Bug',      correctIndex: 2, image: '🐛' },
      { id: 'frog',     label: 'Frog',     correctIndex: 3, image: '🐸' },
      { id: 'snake',    label: 'Snake',    correctIndex: 4, image: '🐍' },
      { id: 'eagle',    label: 'Eagle',    correctIndex: 5, image: '🦅' },
    ],
    visual: {
      wrapperClass: 'bg-gradient-to-b from-green-950 via-green-900 to-emerald-900',
      decorations: [
        { emoji: '🌳', style: { top: '3%',  left: '0%',  fontSize: '5rem',   opacity: '0.3'  } },
        { emoji: '🌳', style: { top: '5%',  right: '0%', fontSize: '6rem',   opacity: '0.25' } },
        { emoji: '🌿', style: { top: '20%', left: '3%',  fontSize: '1.8rem', opacity: '0.35' } },
        { emoji: '🌾', style: { top: '35%', right: '4%', fontSize: '2rem',   opacity: '0.3'  } },
        { emoji: '🌿', style: { top: '55%', left: '5%',  fontSize: '1.5rem', opacity: '0.4'  } },
        { emoji: '🌱', style: { top: '70%', right: '3%', fontSize: '2.5rem', opacity: '0.3'  } },
        { emoji: '🌿', style: { top: '85%', left: '6%',  fontSize: '1.2rem', opacity: '0.35' } },
        { emoji: '🌾', style: { top: '90%', right: '7%', fontSize: '1.8rem', opacity: '0.25' } },
        { emoji: '🦁', style: { top: '38%', left: '46%', fontSize: '8rem',   opacity: '0.05' } },
      ],
      itemCardClass: 'bg-green-900/60 border-green-500/40 backdrop-blur-sm shadow-green-900/40',
      itemTextClass: 'text-green-50',
      zoneNumberClass: 'text-green-400/70',
      zoneEmptyClass: 'border-dashed border-green-500/35 bg-green-900/25',
      poolClass: 'border-green-700/35 bg-green-950/40',
      dropAreaClass: 'bg-emerald-950/40 border-emerald-700/30',
      sectionLabelClass: 'text-green-400/60',
      titleClass: 'text-green-50 drop-shadow-lg',
      subtitleClass: 'text-green-300/70',
      progressFill: '#22c55e',
      progressTrackClass: 'bg-green-950/60',
      backBarClass: 'border-green-800/40 bg-green-950/80 backdrop-blur-sm',
      backButtonClass: 'text-green-300',
    },
  },
]
